name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 0.100.0

      - name: Build site
        run: hugo

      - name: Deploy
        uses: denoland/deployctl@v1
        with:
          project: angora
          entrypoint: https://deno.land/std@0.140.0/http/file_server.ts
          root: public
